backend:
  name: git-gateway
  repo: Folley-05/vip-gatsby
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: Accueil
    label: Accueils
    folder: content/accueil
    create: true
    fields:
      - { name: title, label: Title }
      # - { name: path, label: Path }
      # - { name: date, label: Date, widget: datetime }
      - { name: titre-section, label: titre-section }
      - { name: titre, label: titre }
      - { name: vip-text, label: vip-text }
      - { name: secur-text, label: secur-text }
      - { name: page, label: page }
      - { name: body, label: Body, widget: markdown }
  - name: Securite
    label: Securite
    folder: content/securite
    create: true
    fields:
      - { name: title, label: Title }
      - { name: titre, label: Titre }
      - { name: Detail, label: texte-court }
      - { name: Page, label: Page }
      - { name: Role, label: Role }
      - { name: Sous-titre, label: Sous-titre }
      - { name: body, label: Body, widget: markdown }