backend:
  name: github
  repo: Folley-05/vip-gatsby
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: Pages
    label: Pages
    folder: content/home
    create: true
    fields:
      # - { name: path, label: Path }
      # - { name: date, label: Date, widget: datetime }
      - { name: titre-section, label: titre-section }
      - { name: titre, label: titre }
      - { name: vip-text, label: vip-text }
      - { name: secur-text, label: secur-text }
      - { name: page, label: page }
      - { name: body, label: Body, widget: markdown }